#!/bin/sh
git clone http://git.oschina.net/wuduohangcheng/WifiControl-for-android.git
git clone http://git.oschina.net/mldeng/Android-DirectionalViewPager.git
git clone http://git.oschina.net/mldeng/Android-ViewPagerIndicator.git
git clone http://git.oschina.net/mldeng/Android-PullToRefresh.git
git clone http://git.oschina.net/mldeng/android-square-time.git
git clone http://git.oschina.net/wwwwenhuan/gxpt-android.git
git clone http://git.oschina.net/mldeng/android-async-http.git
git clone http://git.oschina.net/wuduohangcheng/LV-for-android.git
git clone http://git.oschina.net/wuduohangcheng/KeyBoard-for-android.git
git clone http://git.oschina.net/z3787582/yhc-android.git
git clone http://git.oschina.net/chenyoca/android_waterfall.git
git clone http://git.oschina.net/547531167/cordova-android-demo.git
git clone http://git.oschina.net/justzhl/android-sms.git
git clone http://git.oschina.net/hnrainll/PopupMenuDemo.git
git clone http://git.oschina.net/oldfeel/camera.git
git clone http://git.oschina.net/lialun/MusicPlayerProxy.git
git clone http://git.oschina.net/tangs/CalendarLibrary.git
git clone http://git.oschina.net/luckysym/symoid.git
git clone http://git.oschina.net/mldeng/android-universal-image-loader.git
git clone http://git.oschina.net/linpinger/foxbook-android.git
git clone http://git.oschina.net/geliang/android_launcher.git
git clone http://git.oschina.net/tom6886/android-security.git
git clone http://git.oschina.net/songques/HIChat_Android.git
git clone http://git.oschina.net/geliang/Android_LineChartFilpView.git
git clone http://git.oschina.net/wuduohangcheng/LV_Simulator-for-android.git
git clone http://git.oschina.net/wuduohangcheng/Android-Hand-Shank-For-PC.git
git clone http://git.oschina.net/leida/Bangqu-Android-SDK-Demo.git
git clone http://git.oschina.net/hzaccp/openfire-for-android.git
git clone http://git.oschina.net/martinrepo/IMobileGuard.git
git clone http://git.oschina.net/idock/Downloads.git
git clone http://git.oschina.net/enjoy/HideVirtualKey.git
git clone http://git.oschina.net/way/weather.git
git clone http://git.oschina.net/hnrainll/NetMediaPlayer.git
git clone http://git.oschina.net/firefoxmmx/Android_MusicPlayer.git
git clone http://git.oschina.net/hljdrl/ColorTheme.git
git clone http://git.oschina.net/hljdrl/TouchCardPanel.git
git clone http://git.oschina.net/yellowcat/MTextView.git
git clone http://git.oschina.net/ijustyce/sms.git
git clone http://git.oschina.net/122322/SchedulManage.git
git clone http://git.oschina.net/zichuan/Graduate.git
git clone http://git.oschina.net/darin.lao/Android_ChameleonSDK_2.git

